version: '2'

services:
  moodle_db:
    container_name: moodle_db
    ports:
     - "3306:3306"
    environment:
     - MYSQL_DATABASE=moodle
     - MYSQL_USER=moodle
     - MYSQL_PASSWORD=moodle
    image: "centurylink/mysql"
  moodle:
    container_name: moodle
    ports:
     - "5050:80"
    volumes:
     - ./data:/opt/data
    environment:
     - MOODLE_URL=http://127.0.0.1:5050
    image: "jauer/moodle"
    links:
     - moodle_db

